### PR TITLE
fix: various fixes + update languageclient + update dependencies

### LINKED ISSUE #42: DCD installation and spawning issues
There are a couple of issues with DCD:

- [x] If the files are missing serve-d asks to install dcd itself, but there is no notification to the user to notify them if the installation is done. -> The solution to this is to bundle DCD binary like how we do for seve-d. 
	-> Fixed in #43 

- [x] The connections are disposed, refused, or other similar errors. I had this issue in [this comment](https://github.com/Pure-D/atom-ide-d/pull/34#issuecomment-772976300), and I thought the issue is fixed by copying dll files, but after releasing a new version, I am getting similar errors again. Not sure what has changed with DCD!   
	-> Apparently Bypassed in #43 ??

- [x] When dcd does not work properly as described above, if Atom is closed, dcd-server continues to run in the background.  
	-> Apparently Bypassed in #43 ??

- [x] Sometimes DCD seems to be spawned, but the datatips, autocomplete, etc don't return anything like in [this comment](https://github.com/Pure-D/atom-ide-d/pull/34#issuecomment-782770558)
The sent URI is like this:
```
"file:///C:/Users/aminy/Documents/GitHub/JavaScript/atom-ide-d/spec/fixtures/source/app.d"
```

- [ ]  DCD uses a lot of CPU for some reason.

### LINKED ISSUE #49: "serve-d language server for D unable to start"
Also getting a code -13.
I'm on Kubuntu.

### PR DESCRIPTION
**Pull request by aminya**
~Blocked by a new serve-d version:~
 https://github.com/Pure-D/serve-d/pull/136

~Also blocked by the broken binaries of DCD~
https://github.com/dlang-community/DCD/issues/635

Fixes #49 
Fixes #42

### CODE REVIEW

**Review by WebFreak001 — APPROVED** [review]

**Comment by aminya** [comment]
@WebFreak001 I was expecting a new release/beta that includes Windows x64 builds, but this is still not released. I am going to put this on hold, otherwise, I have to build serve-d manually for Windows x64.

**Comment by aminya** [comment]
@WebFreak001 Any news on the new beta?

**Review by aminya — COMMENTED** [review]
Blocked by a new serve-d version:
 https://github.com/Pure-D/serve-d/pull/136

**Review by aminya — COMMENTED** [review]
Also blocked by broken binaries of DCD
https://github.com/dlang-community/DCD/issues/635

**Comment by WebFreak001** [comment]
DCD 0.13.1 is actually broken on OSX (0.13.2 was tagged to fix it)

**Pull request merged**
